version: "3.9"

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017/urvann
      - PORT=5000
      - ALLOW_ORIGIN=http://localhost:5173
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data:
